[package]
name = "AshAdventures"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { version = "0.38.0", features = ["linked"] }
glfw = { version = "0.61.0", features = ["vulkan"] }
glm = "0.3.0"
stb_image_rust = "2.27.2"
tobj = "4.0.3"
